Repository prgrms-web-devcourse/Team_BbungCles_Devnity_FE, pull requests merged in 2021-12, with the labels that each got.

#8 DVT-#7 PR 리뷰어 자동 설정
  .github/CODEOWNERS
Labels: chore

#11 DVT-#10 이모션으로 전역 스타일 테마 설정
  src/App.tsx
  src/assets/theme.ts
  src/types/emotion.d.ts
Labels: config

#12 DVT-#9 라우터 초기 설정
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/MainPage/index.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: config

#14 DVT-#13 formik, yup, react-query, recoil 설치
  package.json
  yarn.lock
Labels: config

#19 DVT-#18 타입스크립트 설정 파일에 테스팅에 필요한 타입 추가
  tsconfig.json
Labels: config

#26 DVT-#25 이모션으로 설정한 전역 스타일을 자동완성이 되도록 타입 지정
  src/assets/theme.ts
Labels: config

#24 DVT-#23 reset.css 및 글로벌 스타일 추가
  index.html
  src/assets/globalStyles.ts
  src/index.tsx
Labels: style

#20 DVT-#16 로그인 페이지 레이아웃 추가
  src/components/Login/Login.test.tsx
  src/components/Login/Login.tsx
  src/components/Login/LoginContainer.tsx
  src/components/Login/styles.ts
  src/pages/LoginPage/index.tsx
  src/routes/Router.tsx
Labels: feat

#22 DVT-#21 회원가입 페이지 레이아웃 추가
  src/components/Signup/Signup.test.tsx
  src/components/Signup/Signup.tsx
  src/components/Signup/SignupContainer.tsx
  src/components/Signup/styles.ts
  src/pages/SignupPage/index.tsx
  src/routes/Router.tsx
Labels: feat

#28 DVT-#27 로그인 페이지 폼 유효성 체크
  src/components/Login/Login.test.tsx
  src/components/Login/Login.tsx
  src/components/Login/LoginContainer.test.tsx
  src/components/Login/LoginContainer.tsx
  src/components/Login/styles.ts
  src/components/Login/types.ts
  src/utils/constants.ts
  tsconfig.json
Labels: feat

#31 DVT-#30 코드 병합 전 자동으로 테스트 실행 및 린트 검사를 위해 CI 구축
  .github/workflows/ci.yml
  package.json
Labels: chore

#32 DVT-#29 회원가입 페이지 폼 유효성 체크
  src/components/Signup/Signup.spec.md
  src/components/Signup/Signup.tsx
  src/components/Signup/SignupContainer.test.tsx
  src/components/Signup/SignupContainer.tsx
  src/components/Signup/styles.ts
  src/components/Signup/types.ts
  src/utils/constants.ts
Labels: feat

#34 DVT-#33 자기소개 프로필 페이지 레이아웃 구성
  src/components/MyProfile/MyProfile.spec.md
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/MyProfileContainer.tsx
  src/components/MyProfile/styles.ts
  src/pages/MyProfilePage/index.tsx
  src/routes/Router.tsx
Labels: feat

#35 DVT-#15 메인페이지 사이드바 및 우측 화면 레이아웃 추가
  .eslintrc.js
  fixtures/userInfo.ts
  jest.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/assets/globalStyles.ts
  src/components/Logo/Logo.tsx
  src/components/Main/Main.spec.md
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/Main/styles.ts
  src/components/Sidebar/Sidebar.spec.md
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContainer.test.tsx
  src/components/Sidebar/SidebarContainer.tsx
  src/components/Sidebar/menuRoutes.ts
  src/components/Sidebar/styles.ts
  src/pages/MainPage/index.test.tsx
  src/pages/MainPage/index.tsx
  src/template/DefaultTemplate.tsx
  src/template/styles.ts
  yarn.lock
Labels: feat

#39 DVT-#38 불필요한 타입 선언 제거
  src/assets/theme.ts
  src/types/emotion.d.ts
Labels: refactor

#40 DVT-#36 회원가입 API 연동
  package.json
  src/App.tsx
  src/components/Signup/Signup.tsx
  src/components/Signup/SignupContainer.test.tsx
  src/components/Signup/SignupContainer.tsx
  src/components/Signup/styles.ts
  src/utils/apis/axiosInstance.ts
  src/utils/apis/signup.ts
  src/utils/constants.ts
  src/utils/yups/signup.ts
  yarn.lock
Labels: feat

#43 DVT-#41 마이페이지 프로필 레이아웃 추가
  .eslintrc.js
  package.json
  src/components/MyProfile/MyProfile.spec.md
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/MyProfileContainer.tsx
  src/components/MyProfile/styles.ts
  src/components/MyProfile/types.ts
  yarn.lock
Labels: feat

#45 DVT-#44 웹 폰트 스포카 한 산스 추가
  src/assets/globalStyles.ts
Labels: config

#47 DVT-#46 회원가입, 로그인 API 연동
  src/components/Login/Login.tsx
  src/components/Login/LoginContainer.test.tsx
  src/components/Login/LoginContainer.tsx
  src/components/Login/styles.ts
  src/components/Signup/Signup.spec.md
  src/components/Signup/Signup.tsx
  src/components/Signup/SignupContainer.tsx
  src/components/Signup/styles.ts
  src/types/commonTypes.ts
  src/utils/apis/axiosInstance.ts
  src/utils/apis/login.ts
  src/utils/apis/signup.ts
  src/utils/constants/login.ts
  src/utils/constants/signup.ts
  src/utils/yups/login.ts
  src/utils/yups/signup.ts
Labels: feat

#48 DVT-#37 유저 자기소개 컴포넌트 추가
  .eslintrc.js
  fixtures/userInfo.ts
  package.json
  src/assets/theme.ts
  src/components/CommentButton/CommentButton.test.tsx
  src/components/CommentButton/CommentButton.tsx
  src/components/CommentButtonAndText/CommentButtonAndText.spec.md
  src/components/CommentButtonAndText/CommentButtonAndText.test.tsx
  src/components/CommentButtonAndText/CommentButtonAndText.tsx
  src/components/CommentButtonAndText/styles.ts
  src/components/LikeButton/LikeButton.test.tsx
  src/components/LikeButton/LikeButton.tsx
  src/components/LikeButtonAndText/LikeButtonAndText.spec.md
  src/components/LikeButtonAndText/LikeButtonAndText.test.tsx
  src/components/LikeButtonAndText/LikeButtonAndText.tsx
  src/components/LikeButtonAndText/styles.ts
  src/components/Logo/Logo.tsx
  src/components/Main/Main.spec.md
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/Main/styles.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContainer.tsx
  src/components/Sidebar/styles.ts
  src/components/Tag/Tag.spec.md
  src/components/Tag/Tag.test.tsx
  src/components/Tag/Tag.tsx
  src/components/UserCard/UserCard.spec.md
  src/components/UserCard/UserCard.test.tsx
  src/components/UserCard/UserCard.tsx
  src/components/UserCard/styles.ts
  src/components/base/Button/index.tsx
  src/components/base/Button/styles.ts
  src/components/base/Image/index.tsx
  src/components/base/Text/index.tsx
  src/constants/course.ts
  src/constants/index.ts
  src/constants/mbti.ts
  src/constants/role.ts
  src/constants/tag.ts
  src/pages/MainPage/index.test.tsx
  src/template/DefaultTemplate.tsx
  src/template/styles.ts
  tsconfig.json
  yarn.lock
Labels: feat

#42 DVT#17 모임 상세 페이지 레이아웃 추가
  src/components/Comment/Comment.tsx
  src/components/Comment/styles.ts
  src/components/CommentForm/CommentForm.tsx
  src/components/CommentForm/styles.ts
  src/components/GatherDetail/GatherDetail.spec.md
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/GatherDetailContainer.tsx
  src/components/GatherDetail/styles.ts
  src/components/GatherDetail/types.ts
  src/components/ProfileBox/ProfileBox.tsx
  src/pages/GatherDetailPage/index.tsx
  src/routes/Router.tsx
Labels: feat

#51 DVT-#50 ProfileBox 오류 수정
  src/components/ProfileBox/ProfileBox.tsx
Labels: fix

#58 DVT-#53 타입스크립트 린트 재설정
  .eslintignore
  .eslintrc.js
  fixtures/userInfo.ts
  package.json
  src/components/Main/Main.tsx
  src/components/UserCard/UserCard.tsx
  src/components/base/Image/index.tsx
  src/constants/course.ts
  src/constants/index.ts
  src/constants/mbti.ts
  src/constants/role.ts
  tsconfig.json
  yarn.lock
Labels: refactor, config

#60 DVT-#57 권한별 라우팅 처리
  src/components/Login/LoginContainer.tsx
  src/constants/errorCode.ts
  src/constants/index.ts
  src/routes/Router.tsx
  src/routes/customRoutes/PrivateRoute.tsx
  src/routes/customRoutes/RestrictRoute.tsx
  src/routes/customRoutes/index.ts
  src/utils/apis/necessaryAuthAxiosInstance.ts
Labels: feat

#63 DVT-#59 메인 화면 헤더의 유저 계정 드롭다운 메뉴 추가
  src/components/Main/Main.spec.md
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/Main/styles.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContainer.test.tsx
  src/components/Sidebar/styles.ts
  src/components/UserCard/UserCard.test.tsx
  src/components/UserDropdownMenu/UserDropdownMenu.spec.md
  src/components/UserDropdownMenu/UserDropdownMenu.test.tsx
  src/components/UserDropdownMenu/UserDropdownMenu.tsx
  src/components/UserDropdownMenu/menuRoutes.ts
  src/components/UserDropdownMenu/styles.ts
  src/components/UserImageAndDropdown/UserImageAndDropdown.spec.md
  src/components/UserImageAndDropdown/UserImageAndDropdown.test.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdown.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.test.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx
  src/components/UserImageAndDropdown/styles.ts
  src/components/UserProfileImage/UserProfileImage.tsx
  src/components/base/Image/index.tsx
  src/hooks/useToggle.ts
  src/types/commonTypes.ts
Labels: feat

#69 DVT-#68 라우트 경로 상수화
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/SidebarContainer.test.tsx
  src/components/Sidebar/menuRoutes.ts
  src/components/Signup/SignupContainer.tsx
  src/components/UserDropdownMenu/UserDropdownMenu.test.tsx
  src/components/UserDropdownMenu/menuRoutes.ts
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.test.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx
  src/constants/index.ts
  src/constants/routes.ts
  src/routes/Router.tsx
  src/routes/customRoutes/PrivateRoute.tsx
  src/routes/customRoutes/RestrictRoute.tsx
Labels: ♻️ refactor

#70 DVT-#66 마이프로필 API 연동
  src/App.tsx
  src/components/MyProfile/MyProfile.spec.md
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/MyProfileContainer.tsx
  src/components/MyProfile/formik.ts
  src/components/MyProfile/styles.ts
  src/components/MyProfile/types.ts
  src/constants/common.ts
  src/constants/errorCode.ts
  src/constants/index.ts
  src/constants/myProfile.ts
  src/types/commonTypes.ts
  src/utils/apis/index.ts
  src/utils/apis/myProfile.ts
  src/utils/apis/necessaryAuthAxiosInstance.ts
Labels: feat

#71 DVT-#52 모집게시판 메인페이지, 카테고리별 메인페이지 레이아웃 추가
  src/components/ApplicantCountText/index.tsx
  src/components/GatherList/GatherList.tsx
  src/components/GatherList/styles.ts
  src/components/GatherMain/GatherMain.spec.md
  src/components/GatherMain/GatherMain.tsx
  src/components/GatherMain/GatherMainContainer.tsx
  src/components/GatherMain/styles.ts
  src/components/PeriodText/index.tsx
  src/components/ViewText/index.tsx
  src/constants/categoryName.ts
  src/constants/index.ts
  src/pages/GatherClubPage/index.tsx
  src/pages/GatherPage/index.tsx
  src/pages/GatherProjectPage/index.tsx
  src/pages/GatherStudyPage/index.tsx
  src/routes/Router.tsx
Labels: feat

#76 DVT-#54 메인 화면 맵각코 추가
  .npmrc
  __mocks__/fileMock.ts
  __mocks__/styleMock.ts
  fixtures/map.ts
  index.html
  jest.config.js
  package-lock.json
  package.json
  src/assets/images/ic_arrow_drop_down_circle_48px.svg
  src/components/Main/Main.spec.md
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/Main/styles.ts
  src/components/Mapbox/Mapbox.spec.md
  src/components/Mapbox/Mapbox.tsx
  src/components/Mapbox/index.scss
  src/components/Mapgakco/Mapgakco.tsx
  src/components/Sidebar/Sidebar.spec.md
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContainer.test.tsx
  src/components/Sidebar/menuRoutes.ts
  src/components/UserCard/styles.ts
  src/constants/index.ts
  src/pages/MainPage/index.test.tsx
  src/types/MapTypes.ts
  src/utils/map/index.ts
  yarn.lock
Labels: feat

#75 DVT-#74 마이프로필 카카오지도 연동
  src/components/MyProfile/MyProfile.spec.md
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/MyProfileContainer.tsx
  src/components/MyProfile/styles.ts
  src/components/MyProfile/types.ts
  src/constants/common.ts
  src/types/commonTypes.ts
Labels: feat

#72 DVT-#67 Input Base 컴포넌트 개발
  src/assets/theme.ts
  src/components/MyProfile/MyProfile.tsx
  src/components/base/Input/index.tsx
  src/components/base/Input/styles.ts
  src/components/base/Input/types.ts
Labels: feat

#78 DVT-#77 Github Actions 워크플로우를 트리거별로 분리
  .github/pull_request_template.md
  .github/workflows/on-pull-request.yml
  .github/workflows/on-push.yml
Labels: chore

#81 DVT-#55 메인 화면 모집 게시판 추가
  fixtures/gather.ts
  fixtures/userInfo.ts
  src/components/Main/Main.tsx
  src/components/Main/styles.ts
  src/components/ProfileBox/ProfileBox.tsx
  src/components/UserCard/UserCard.tsx
Labels: feat

#80 DVT-#79 카카오맵 센터포지션 null 체크
  src/components/MyProfile/MyProfileContainer.tsx
Labels: ♻️ refactor

#84 DVT-#83 마이프로필 마크다운 에디터 연동
  package.json
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/styles.ts
  src/components/base/MarkdownEditor/index.tsx
  src/hooks/useToastUi.ts
  src/utils/apis/index.ts
  src/utils/apis/markdown.ts
  webpack.config.js
  yarn.lock
Labels: feat

#91 DVT-#87 자신의 정보 recoil로 관리
  .eslintrc.js
  src/App.tsx
  src/atoms/index.ts
  src/atoms/user.ts
  src/components/Main/Main.test.tsx
  src/components/MyProfile/types.ts
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.test.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx
  src/pages/MainPage/index.test.tsx
  src/template/DefaultTemplate.tsx
Labels: feat

#90 DVT-#82 사이드바 반응형 레이아웃 추가
  fixtures/gather.ts
  jest.config.js
  package.json
  src/assets/lotties/christmas-dog.json
  src/assets/lotties/music-dog.json
  src/assets/lotties/snowman.json
  src/assets/media.ts
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/Main/styles.ts
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContainer.test.tsx
  src/components/Sidebar/SidebarIcon.tsx
  src/components/Sidebar/styles.ts
  src/components/UserCard/UserCard.test.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx
  src/components/base/Button/styles.ts
  src/pages/MainPage/index.test.tsx
  tsconfig.json
  yarn.lock
Labels: feat

#93 DVT-#85 데둥이 소개 페이지 리스트 레이아웃
  fixtures/selectDatas.ts
  fixtures/userList.ts
  src/assets/media.ts
  src/components/CommentButton/CommentButton.tsx
  src/components/LikeButton/LikeButton.tsx
  src/components/MyProfile/MyProfile.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/UserCard/styles.ts
  src/components/UserList/UserList.tsx
  src/components/UserList/UserListContainer.tsx
  src/components/UserList/styles.ts
  src/components/UserList/types.ts
  src/components/base/Button/styles.ts
  src/components/base/Input/index.tsx
  src/components/base/Input/types.ts
  src/constants/common.ts
  src/pages/UserListPage/index.tsx
  src/routes/Router.tsx
  src/routes/customRoutes/PrivateRoute.tsx
Labels: style

#94 DVT-#73 모집 등록 모달 추가
  package.json
  src/components/GatherMain/GatherMain.tsx
  src/components/GatherMain/GatherMainContainer.tsx
  src/components/GatherMain/styles.ts
  src/components/GatherRegisterForm/GatherRegisterForm.tsx
  src/components/GatherRegisterForm/GatherRegistorFormContainer.tsx
  src/components/GatherRegisterForm/styles.ts
  src/components/SearchForm/index.tsx
  src/components/SearchForm/styles.ts
  src/components/base/Button/index.tsx
  src/components/base/Input/styles.ts
  src/components/base/Input/types.ts
  src/components/base/Modal/index.tsx
  src/components/base/Modal/styles.ts
Labels: feat

#96 DVT-#92 메인 페이지 API 연결
  fixtures/gather.ts
  fixtures/userInfo.ts
  src/atoms/auth.ts
  src/atoms/user.ts
  src/components/GatherList/GatherList.tsx
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/Main/MainContainer.tsx
  src/components/Main/styles.ts
  src/components/Mapbox/Mapbox.tsx
  src/components/Mapgakco/Mapgakco.tsx
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContainer.test.tsx
  src/components/Sidebar/styles.ts
  src/components/UserCard/UserCard.test.tsx
  src/components/UserCard/UserCard.tsx
  src/components/base/Text/index.tsx
  src/constants/api.ts
  src/constants/index.ts
  src/hooks/useGatherSuggestions.ts
  src/hooks/useUserSuggetions.ts
  src/pages/MainPage/index.test.tsx
  src/pages/MainPage/index.tsx
  src/routes/Router.tsx
  src/routes/customRoutes/PrivateRoute.tsx
  src/types/Gather.ts
  src/types/gather.ts
  src/types/mapTypes.ts
  src/types/userInfo.ts
  src/utils/apis/index.ts
  src/utils/apis/main.ts
  src/utils/apis/mocks/index.ts
  src/utils/apis/mocks/main.ts
  src/utils/map/index.ts
Labels: feat

#99 DVT-#86 데둥이 소개 페이지 상세
  src/components/LikeButton/LikeButton.tsx
  src/components/LikeButtonAndText/LikeButtonAndText.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/UserDetail/Comment/index.tsx
  src/components/UserDetail/Comment/styles.ts
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/UserDetailContainer.tsx
  src/components/UserDetail/styles.ts
  src/components/UserDetail/types.ts
  src/components/UserList/UserList.tsx
  src/components/UserList/UserListContainer.tsx
  src/components/UserList/styles.ts
  src/components/UserList/types.ts
  src/components/base/MarkdownEditor/index.tsx
  src/constants/common.ts
  src/constants/routes.ts
  src/hooks/useIntroduction.ts
  src/hooks/useMyProfile.ts
  src/pages/UserDetailPage/index.tsx
  src/routes/Router.tsx
  src/template/DefaultTemplate.tsx
  src/utils/apis/introductions.ts
Labels: feat

#98 DVT-#89 데둥여지도 페이지 추가
  fixtures/map.ts
  fixtures/userInfo.ts
  fixtures/userMapInfo.ts
  src/atoms/user.ts
  src/components/Main/Main.tsx
  src/components/Mapbox/Mapbox.tsx
  src/components/Mapbox/index.scss
  src/components/UsersMap/UsersMap.spec.md
  src/components/UsersMap/UsersMap.tsx
  src/components/UsersMap/UsersMapContainer.tsx
  src/pages/UsersMapPage/UsersMapPage.spec.md
  src/pages/UsersMapPage/index.tsx
  src/routes/Router.tsx
  src/types/mapTypes.ts
  src/types/userInfo.ts
  src/utils/map/control.ts
  src/utils/map/index.ts
  src/utils/map/marker.ts
  src/utils/map/overlay.ts
Labels: feat

#103 DVT-#102 메인 페이지 API 연동
  .eslintrc.js
  __mocks__/axios.ts
  fixtures/userInfo.ts
  fixtures/userList.ts
  package.json
  src/App.tsx
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/UserCardList/UserCardList.spec.md
  src/components/UserCardList/UserCardList.test.tsx
  src/components/UserCardList/UserCardList.tsx
  src/constants/api.ts
  src/hooks/useGatherSuggestions.ts
  src/hooks/useUserSuggetions.ts
  src/types/userInfo.ts
  src/utils/apis/main.ts
  src/utils/apis/mocks/main.ts
  yarn.lock
Labels: feat

#104 DVT-#100 데둥이 소개 API 연동
  src/assets/theme.ts
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/MyProfileContainer.tsx
  src/components/MyProfile/types.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/styles.ts
  src/components/UserDetail/Comment/index.tsx
  src/components/UserDetail/Comment/styles.ts
  src/components/UserDetail/UserDetail.spec.md
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/UserDetailContainer.tsx
  src/components/UserDetail/styles.ts
  src/components/UserDetail/types.ts
  src/components/UserList/UserList.spec.md
  src/components/UserList/UserList.tsx
  src/components/UserList/UserListContainer.tsx
  src/components/UserList/types.ts
  src/components/base/MarkdownEditor/index.tsx
  src/constants/common.ts
  src/constants/tag.ts
  src/hooks/useFilteredUserList.ts
  src/hooks/useIntroduction.ts
  src/hooks/useMutationUserDeleteComment.ts
  src/hooks/useMutationUserDeleteLike.ts
  src/hooks/useMutationUserDetailComment.ts
  src/hooks/useMutationUserLike.ts
  src/hooks/useMutationUserModifyComment.ts
  src/utils/apis/introductions.ts
Labels: feat

#106 DVT-#88 E2E 테스트를 위한 Cypress 설정
  .eslintrc.js
  .gitignore
  cypress.json
  cypress/fixtures/signupFormData.json
  cypress/integration/login.spec.ts
  cypress/integration/signup.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  jest.config.js
  package.json
  src/App.tsx
  yarn.lock
Labels: config

#109 DVT-#105 데둥이 소개 무한스크롤
  package.json
  src/assets/media.ts
  src/components/Login/LoginContainer.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/UserDetail/Comment/index.tsx
  src/components/UserDetail/Comment/styles.ts
  src/components/UserList/UserList.tsx
  src/components/UserList/UserListContainer.tsx
  src/components/UserList/styles.ts
  src/components/UserList/types.ts
  src/constants/common.ts
  src/hooks/useUserInfiniteQuery.ts
  src/utils/apis/introductions.ts
  yarn.lock
Labels: feat

#111 DVT-#110 페이지별 사이드바 visible 처리
  src/atoms/sidebarVisible.ts
  src/pages/GatherClubPage/index.tsx
  src/pages/GatherDetailPage/index.tsx
  src/pages/GatherPage/index.tsx
  src/pages/GatherProjectPage/index.tsx
  src/pages/GatherStudyPage/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyProfilePage/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/UserDetailPage/index.tsx
  src/pages/UserListPage/index.tsx
  src/pages/UsersMapPage/index.tsx
  src/template/DefaultTemplate.tsx
Labels: feat

#113 DVT-#108 맵각코 페이지 레이아웃 추가
  cypress/integration/login.spec.ts
  src/components/Mapbox/Mapbox.tsx
  src/components/Mapbox/index.scss
  src/components/Mapgakco/Mapgakco.tsx
  src/components/MapgakcoMap/MapgakcoMap.spec.md
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/MapgakcoMapContainer.tsx
  src/components/MapgakcoMap/PlaceSearchForm.tsx
  src/components/MapgakcoMap/styles.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/UsersMap/UsersMap.tsx
  src/components/base/Button/index.tsx
  src/components/base/Input/styles.ts
  src/components/base/Input/types.ts
  src/constants/mapApi.ts
  src/hooks/useMapClick.ts
  src/hooks/useSearchResults.ts
  src/pages/MapgakcoMapPage/index.tsx
  src/routes/Router.tsx
  src/utils/apis/index.ts
  src/utils/apis/mapAxiosInstance.ts
  src/utils/apis/search.ts
  src/utils/map/equal.ts
  src/utils/map/index.ts
  src/utils/map/marker.ts
  src/utils/map/overlay.ts
  src/utils/map/place.ts
Labels: feat

#117 DVT-#116 파일명 케이스 오타 수정
  fixtures/gather.ts
Labels: fix

#118 DVT-#112 사용자, 자기소개 validation 적용
  src/components/MyProfile/MyProfile.tsx
  src/components/Signup/styles.ts
  src/components/UserDetail/Comment/index.tsx
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/styles.ts
  src/components/base/Input/index.tsx
  src/components/base/Input/types.ts
  src/constants/common.ts
  src/constants/signup.ts
  src/utils/yups/login.ts
  src/utils/yups/signup.ts
Labels: feat

#123 DVT-#121 파일명이 오타인 파일 삭제
  src/types/Gather.ts
Labels: fix

#126 DVT-#125 Vercel에 SPA 앱을 배포하기 위해 필요한 설정 파일 추가
  vercel.json
Labels: config

#130 DVT#97 모집게시판 상세페이지 API 연동
  fixtures/gather.ts
  src/components/Comment/Comment.tsx
  src/components/Comment/styles.ts
  src/components/CommentForm/CommentForm.tsx
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/GatherDetailContainer.tsx
  src/components/GatherDetail/styles.ts
  src/components/GatherDetail/types.ts
  src/components/GatherList/GatherList.tsx
  src/components/GatherMain/GatherMain.tsx
  src/components/GatherMain/GatherMainContainer.tsx
  src/components/GatherRegisterForm/GatherRegisterForm.tsx
  src/components/GatherRegisterForm/GatherRegistorFormContainer.tsx
  src/components/GatherRegisterForm/styles.ts
  src/constants/categoryName.ts
  src/constants/gatherStatus.ts
  src/constants/index.ts
  src/constants/routes.ts
  src/hooks/useAddGather.ts
  src/hooks/useApplyGather.ts
  src/hooks/useCancelApplyGather.ts
  src/hooks/useCreateGatherComment.ts
  src/hooks/useDeleteComment.ts
  src/hooks/useDeleteGather.ts
  src/hooks/useEditComment.ts
  src/hooks/useFilteredGathers.ts
  src/hooks/useGetGatherDetail.ts
  src/routes/Router.tsx
  src/types/comment.ts
  src/types/gather.ts
  src/types/simpleUserInfo.ts
  src/utils/apis/gather.ts
  src/utils/apis/index.ts
Labels: feat

#101 DVT#95 내 모집 관리 페이지 추가
  src/assets/media.ts
  src/components/GatherList/GatherList.tsx
  src/components/GatherList/styles.ts
  src/components/MyGather/MyGather.tsx
  src/components/MyGather/MyGatherContainer.tsx
  src/components/MyGather/styles.ts
  src/components/ProfileBox/ProfileBox.tsx
  src/components/ViewText/index.tsx
  src/components/base/Text/index.tsx
  src/pages/MyGatherPage/index.tsx
  src/routes/Router.tsx
Labels: feat

#131 DVT-#107 관리자 화면 회원가입 초대링크 생성
  package.json
  src/components/Admin/Admin.tsx
  src/components/Admin/AdminContainer.tsx
  src/components/Admin/styles.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarIcon.tsx
  src/components/Sidebar/menuRoutes.ts
  src/constants/admin.ts
  src/constants/common.ts
  src/constants/index.ts
  src/hooks/useCopyClipboard.ts
  src/hooks/useFilteredUserList.ts
  src/hooks/useMutationInviteLink.ts
  src/hooks/useQueryInviteLink.ts
  src/hooks/useUserInfiniteQuery.ts
  src/pages/AdminPage/index.tsx
  src/routes/Router.tsx
  src/utils/apis/admin.ts
  src/utils/apis/introductions.ts
  src/utils/yups/admin.ts
  yarn.lock
Labels: feat

#132 DVT-#120 404 페이지 작업
  src/assets/lotties/404-error.json
  src/pages/NotFoundPage/index.tsx
  src/pages/NotFoundPage/styles.ts
  src/routes/Router.tsx
Labels: feat

#134 DVT-#114 맵각코 페이지 데둥이 위치 필터 기능 추가
  src/components/Mapbox/Mapbox.tsx
  src/components/Mapbox/customOverlayMarker.scss
  src/components/Mapbox/imageMarker.scss
  src/components/MapgakcoMap/FilterButton.tsx
  src/components/MapgakcoMap/MapgakcoMap.spec.md
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/MapgakcoMapContainer.tsx
  src/components/MapgakcoMap/styles.ts
  src/utils/map/index.ts
  src/utils/map/overlay.ts
Labels: feat

#136 DVT-#135 탑바를 디폴트 템플릿으로 위치 변경
  src/atoms/topbarVisble.ts
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MapgakcoMapPage/index.tsx
  src/pages/MyProfilePage/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/UsersMapPage/index.tsx
  src/template/DefaultTemplate.tsx
  src/template/styles.ts
Labels: feat

#137 DVT-#133 개발 서버 CI/CD 설정 (AWS S3)
  .github/workflows/deploy-dev.yml
  .github/workflows/validate.yml
Labels: config

#139 DVT-#122 맵각코 등록
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoRegister/index.tsx
  src/components/MapgakcoRegister/stlyes.ts
  src/components/base/Button/index.tsx
  src/components/base/Input/index.tsx
  src/components/base/Input/types.ts
  src/components/base/Modal/styles.ts
  src/hooks/useMutationMapgakcoRegister.ts
  src/utils/apis/mapgakco.ts
Labels: feat

#142 DVT-#141 탑바 스타일을 전역 상태로 관리
  src/atoms/topbarBgColor.ts
  src/components/Main/styles.ts
  src/pages/AdminPage/index.tsx
  src/pages/GatherClubPage/index.tsx
  src/pages/GatherPage/index.tsx
  src/pages/GatherProjectPage/index.tsx
  src/pages/GatherStudyPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyGatherPage/index.tsx
  src/pages/MyProfilePage/index.tsx
  src/pages/UserListPage/index.tsx
  src/template/DefaultTemplate.tsx
  src/template/styles.ts
Labels: feat

#144 DVT-#127내 모임 관리 페이지 API 연동
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/styles.ts
  src/components/GatherList/GatherList.tsx
  src/components/GatherList/styles.ts
  src/components/MyGather/MyGather.tsx
  src/components/MyGather/MyGatherContainer.tsx
  src/components/MyGather/styles.ts
  src/components/PeriodText/index.tsx
  src/components/ProfileBox/ProfileBox.tsx
  src/constants/categoryName.ts
  src/hooks/useMyAppliedGather.ts
  src/hooks/useMyPostingGather.ts
  src/types/gather.ts
  src/utils/apis/gather.ts
Labels: feat

#150 DVT-#149 .env 개발서버 DOMAIN 추가
  .github/workflows/deploy-dev.yml
Labels: config

#147 DVT-#145 맵각코 피드백 반영
  package.json
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoRegister/index.tsx
  src/components/MapgakcoRegister/stlyes.ts
  src/hooks/useToastUi.ts
  yarn.lock
Labels: feat

#151 DVT-#115 맵각코 페이지 맵각코 조회 기능 추가
  fixtures/userInfo.ts
  src/assets/theme.ts
  src/components/Mapbox/Mapbox.tsx
  src/components/Mapbox/mapgakcoOverlay.scss
  src/components/MapgakcoMap/MapgakcoDetail/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/styles.ts
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/MapgakcoMapContainer.tsx
  src/components/MapgakcoMap/MapgakcoMarker.tsx
  src/components/MapgakcoMap/UserMarker.tsx
  src/components/base/Modal/index.tsx
  src/hooks/useClickAway.ts
  src/hooks/useMapgakcos.ts
  src/template/DefaultTemplate.tsx
  src/template/styles.ts
  src/types/mapTypes.ts
  src/utils/apis/index.ts
  src/utils/apis/mapgakco.ts
  src/utils/apis/mocks/index.ts
  src/utils/apis/mocks/mapgakcos.ts
  src/utils/date.ts
  src/utils/map/overlay.ts
Labels: feat

#153 DVT-#146 react-query 에러 처리
  src/App.tsx
  src/components/Login/LoginContainer.tsx
  src/components/MyProfile/MyProfileContainer.tsx
  src/components/Signup/SignupContainer.tsx
  src/components/UserList/UserListContainer.tsx
  src/hooks/useCustomQueryClient.ts
  src/hooks/useIntroduction.ts
  src/hooks/useMutationMapgakcoRegister.ts
  src/hooks/useMutationUserDeleteLike.ts
  src/hooks/useMutationUserLike.ts
  src/hooks/useMutationUserModifyComment.ts
  src/hooks/useQueryCheckValidLink.ts
  src/hooks/useUserInfiniteQuery.ts
Labels: feat

#148 DVT-#128 모집 게시글 댓글 레이아웃 수정
  src/components/GatherDetail/Comment/index.tsx
  src/components/GatherDetail/Comment/styles.ts
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/GatherDetailContainer.tsx
  src/components/GatherDetail/styles.ts
  src/components/GatherDetail/types.ts
  src/components/PeriodText/index.tsx
  src/constants/common.ts
  src/constants/index.ts
  src/hooks/useCloseGather.ts
  src/hooks/useCreateGatherComment.ts
  src/hooks/useDeleteComment.ts
  src/hooks/useEditComment.ts
  src/hooks/useGetGatherDetail.ts
Labels: feat

#156 DVT-#154 레이아웃 피드백 반영
  src/components/MapgakcoRegister/index.tsx
  src/components/MapgakcoRegister/stlyes.ts
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/styles.ts
  src/components/UserDetail/Comment/index.tsx
  src/components/UserDetail/Comment/styles.ts
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/styles.ts
  src/components/UserList/styles.ts
Labels: fix

#155 DVT-#152 맵각코 페이지에서 맵각코 조회 및 상세 조회 기능을 추가한다.
  src/components/Mapbox/mapgakcoOverlay.scss
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailContainer.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnEdit/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnEdit/styles.ts
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/styles.ts
  src/components/MapgakcoMap/MapgakcoDetail/index.tsx
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/MapgakcoMarker.tsx
  src/components/base/Button/index.tsx
  src/constants/api.ts
  src/hooks/useMapgakcoDetailQuery.tsx
  src/hooks/useMapgakcoFormik.ts
  src/hooks/useMutationMapgakcoPatch.ts
  src/utils/apis/index.ts
  src/utils/apis/mapgakco.ts
  src/utils/apis/mocks/index.ts
  src/utils/apis/mocks/mapgakcos.ts
Labels: feat

#161 DVT-#157 어드민이 생성한 회원가입 링크 정합성 체크 확인
  src/components/GatherDetail/GatherDetailContainer.tsx
  src/components/Login/LoginContainer.tsx
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/styles.ts
  src/components/Sidebar/Sidebar.test.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContainer.test.tsx
  src/components/Sidebar/menuRoutes.ts
  src/components/Signup/Signup.tsx
  src/components/Signup/SignupContainer.tsx
  src/components/Signup/styles.ts
  src/hooks/useQueryCheckValidLink.ts
Labels: feat

#164 DVT-#162 맵각코 페이지 조회 API 연동
  .babelrc
  package.json
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailContainer.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnEdit/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/styles.ts
  src/components/MapgakcoMap/MapgakcoMapContainer.tsx
  src/constants/api.ts
  src/constants/coords.ts
  src/constants/index.ts
  src/hooks/useMapgakcoDetailQuery.tsx
  src/hooks/useMapgakcos.ts
  src/hooks/useMutationMapgakcoPatch.ts
  src/types/mapgakco.ts
  src/utils/apis/index.ts
  src/utils/apis/mapgakco.ts
  webpack.config.js
  yarn.lock
Labels: feat

#167 DVT-#158 모집게시판 게시글 등록 모달 수정
  src/assets/theme.ts
  src/components/GatherMain/GatherMain.tsx
  src/components/GatherRegisterForm/GatherRegisterForm.tsx
  src/components/GatherRegisterForm/GatherRegistorFormContainer.tsx
  src/components/GatherRegisterForm/styles.ts
  src/hooks/useAddGather.ts
Labels: fix

#170 DVT-#159 모집게시글 상세페이지 댓글 수정
  src/components/GatherDetail/Comment/index.tsx
  src/components/GatherDetail/Comment/styles.ts
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/styles.ts
  src/components/UserDetail/styles.ts
  src/hooks/useCreateGatherComment.ts
  src/hooks/useDeleteComment.ts
  src/hooks/useEditComment.ts
Labels: fix

#168 DVT-#163 레이아웃 수정
  src/assets/theme.ts
  src/components/Main/styles.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/Sidebar/styles.ts
  src/components/UserCard/UserCard.tsx
  src/components/UserCard/styles.ts
  src/components/UserList/UserList.tsx
  src/components/UserList/styles.ts
  src/constants/common.ts
  src/hooks/useMutationInviteLink.ts
  src/hooks/useMutationUserDeleteComment.ts
  src/hooks/useMutationUserDetailComment.ts
  src/hooks/useQueryInviteLink.ts
  src/hooks/useToastUi.ts
  src/pages/MainPage/index.tsx
  src/routes/Router.tsx
  src/routes/customRoutes/RestrictRoute.tsx
Labels: style

#171 DVT-#166 맵각코 페이지에서 데둥이 조회 API 연동
  src/components/Mapbox/customOverlayMarker.scss
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/MapgakcoMapContainer.tsx
  src/components/MapgakcoMap/UserMarker.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/styles.ts
  src/components/UserImageAndDropdown/UserImageAndDropdown.test.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdown.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.test.tsx
  src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx
  src/components/UsersMap/UsersMap.tsx
  src/components/UsersMap/UsersMapContainer.tsx
  src/constants/api.ts
  src/hooks/useHover.ts
  src/hooks/useUsersLocationsFormik.ts
  src/hooks/useUsersLocationsQuery.ts
  src/types/userLocation.ts
  src/utils/apis/index.ts
  src/utils/apis/user.ts
  src/utils/map/overlay.ts
Labels: feat

#176 DVT-#174 유저 드랍다운 메뉴 버그 해결
  src/components/UserImageAndDropdown/UserImageAndDropdown.tsx
Labels: fix

#173 DVT-#172 레이아웃 다듬기
  package.json
  src/assets/theme.ts
  src/components/Admin/Admin.tsx
  src/components/GatherDetail/Comment/index.tsx
  src/components/Main/Main.test.tsx
  src/components/Main/styles.ts
  src/components/MapgakcoRegister/index.tsx
  src/components/MapgakcoRegister/stlyes.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/menuRoutes.ts
  src/components/Sidebar/styles.ts
  src/components/UserCardList/UserCardList.test.tsx
  src/components/UserCardList/UserCardList.tsx
  src/components/UserDetail/Comment/index.tsx
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/types.ts
  src/hooks/useDayjs.ts
  src/hooks/useMutationInviteLink.ts
  src/pages/MainPage/index.test.tsx
  yarn.lock
Labels: style

#177 DVT-#174 프로덕트 환경에 따른 API URL 환경 변수 설정
  package.json
  src/components/Admin/Admin.tsx
  src/components/UsersMap/UsersMap.tsx
  src/utils/apis/necessaryAuthAxiosInstance.ts
  src/utils/apis/unnecessaryAuthAxiosInstance.ts
  webpack.config.js
Labels: fix, config

#179 DVT-#178 메인 페이지에 맵각코 요약 컴포넌트 렌더링
  src/App.tsx
  src/components/Main/Main.test.tsx
  src/components/Main/Main.tsx
  src/components/Main/MainContainer.tsx
  src/components/Main/MapgakcoSummary/MapgakcoSummaryContainer.tsx
  src/components/Main/styles.ts
  src/components/MapgakcoMap/MapgakcoMap.tsx
Labels: feat

#182 DVT-#181 클립보드 버그 수정
  package.json
  src/components/Admin/Admin.tsx
  yarn.lock
Labels: fix

#184 DVT-#183 맵각코 상세 정보에서 달력이 뭉개지는 현상을 고치기 위해 모달 너비 조절
  src/components/MapgakcoMap/MapgakcoMap.tsx
Labels: fix

#180 DVT-#160 무한스크롤 구현 및 수정
  src/assets/theme.ts
  src/components/CommentText/index.tsx
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/styles.ts
  src/components/GatherList/GatherList.tsx
  src/components/GatherList/styles.ts
  src/components/GatherMain/GatherMain.tsx
  src/components/GatherMain/GatherMainContainer.tsx
  src/components/MyGather/MyGather.tsx
  src/components/SearchForm/index.tsx
  src/constants/categoryName.ts
  src/constants/index.ts
  src/hooks/useAddGather.ts
  src/hooks/useCancelApplyGather.ts
  src/hooks/useCloseGather.ts
  src/hooks/useDeleteGather.ts
  src/hooks/useFilteredGathers.ts
  src/hooks/useGatherInfiniteQuery.ts
  src/utils/apis/gather.ts
Labels: feat

#188 DVT-#187 placeholder 이미지 추가
  src/components/UserCard/UserCard.tsx
Labels: fix

#193 DVT-#191 맵각코 상세 페이지 라우팅 연결
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailContainer.tsx
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/routes/Router.tsx
Labels: feat, fix

#195 DVT-#194 메인화면 자기소개 흔들리는 레이아웃 버그해결
  src/components/UserCardList/UserCardList.tsx
Labels: fix

#197 DVT-#196 데둥이소개 상세 글씨 깨지는 현상 수정
  logo.png
  src/components/UserDetail/UserDetail.tsx
  src/components/UserDetail/styles.ts
Labels: style

#199 DVT-#198 메인화면 자기소개 에러 수정
  src/components/UserCardList/UserCardList.tsx
Labels: fix

#201 DVT-#200 맵각코 상세 페이지를 모달에서 슬라이더로 변경 및 작성자 아이콘 추가
  src/assets/theme.ts
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailContainer.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/styles.ts
  src/components/MapgakcoMap/MapgakcoDetail/styles.ts
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/styles.ts
Labels: feat

#206 README 문서 작성
  README.md
Labels: docs
