Repository prgrms-web-devcourse/Team_BbungCles_Devnity_FE, pull requests merged in 2022-02, with the labels that each got.

#231 DVT-#230 모집게시글 목록 로직함수 리팩토링
  src/components/GatherList/GatherList.tsx
  src/components/GatherMain/GatherMain.tsx
Labels: ♻️ refactor

#235 DVT-#233 데둥여지도 사용자 필터링 목록 UI 추가
  fixtures/userData.ts
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/UserProfileImage/UserProfileImage.tsx
  src/components/UsersMap/SearchedUsers/SearchedUsers.styles.tsx
  src/components/UsersMap/SearchedUsers/SearchedUsers.tsx
  src/components/UsersMap/UsersMap.spec.md
  src/components/UsersMap/UsersMap.styles.ts
  src/components/UsersMap/UsersMap.tsx
  src/components/UsersMap/UsersMapContainer.tsx
  src/components/base/Input/styles.ts
  src/components/base/Input/types.ts
  src/constants/common.ts
  src/types/userLocation.ts
  src/utils/map/overlay.ts
  src/utils/validator.test.ts
  src/utils/validator.ts
Labels: feat

#237 DVT-#236 사이드바에 프로필 메뉴 추가 및 데둥여지도 기수 셀렉트 박스의 옵션 수정
  src/components/Sidebar/SidebarIcon.tsx
  src/components/Sidebar/menuRoutes.ts
  src/components/UsersMap/UsersMap.tsx
Labels: feat

#241 DVT-#240 사이드바 및 탑바의 가시 여부를 조절하는 불필요한 useEffect 제거
  src/pages/AdminPage/index.tsx
  src/pages/GatherClubPage/index.tsx
  src/pages/GatherDetailPage/index.tsx
  src/pages/GatherPage/index.tsx
  src/pages/GatherProjectPage/index.tsx
  src/pages/GatherStudyPage/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MapgakcoMapPage/index.tsx
  src/pages/MyGatherPage/index.tsx
  src/pages/MyProfilePage/index.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/UserDetailPage/index.tsx
  src/pages/UserListPage/index.tsx
  src/pages/UsersMapPage/index.tsx
Labels: ♻️ refactor

#239 DVT-#192 모집게시글 상세페이지 UI 변경
  .eslintrc.js
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/GatherDetailContainer.tsx
  src/components/GatherDetail/styles.ts
  src/components/GatherDetail/types.ts
  src/components/GatherList/GatherList.tsx
  src/components/GatherMain/GatherMain.tsx
  src/components/GatherRegisterForm/GatherRegisterForm.tsx
  src/components/GatherRegisterForm/GatherRegistorFormContainer.tsx
  src/components/base/Divider/index.tsx
Labels: style

#243 DVT-#242 맵각코 상세 등록 모달에 지정된 장소 추가 및 맵각코 주소 검색 결과 빈칸 초기화
  src/components/MapgakcoMap/MapFloatControl/index.tsx
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/PlaceSearchForm/PlaceSearchForm.tsx
  src/components/MapgakcoMap/PlaceSearchForm/SearchResultList.tsx
  src/components/MapgakcoRegister/index.tsx
  src/constants/searchApi.ts
  src/hooks/useCoord2Address.ts
  src/pages/AdminPage/index.tsx
  src/pages/GatherClubPage/index.tsx
  src/pages/GatherDetailPage/index.tsx
  src/pages/GatherPage/index.tsx
  src/pages/GatherProjectPage/index.tsx
  src/pages/GatherStudyPage/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MapgakcoMapPage/index.tsx
  src/pages/MyGatherPage/index.tsx
  src/pages/MyProfilePage/index.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/UserDetailPage/index.tsx
  src/pages/UserListPage/index.tsx
  src/pages/UsersMapPage/index.tsx
  src/types/coord2Address.ts
  src/types/place.ts
  src/utils/apis/coord2Address.ts
  src/utils/map/coord.ts
Labels: feat, fix
