Repository prgrms-web-devcourse/Team_BbungCles_Devnity_FE, pull requests merged in 2022-01, with the labels that each got.

#208 DVT-#203 맵각코 페이지에서 검색을 마치면 검색 결과 제거
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/PlaceSearchForm.tsx
Labels: fix

#210 DVT-#209 맵각코 지도 컴포넌트 리팩터
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/ParticipantList/ParticipantList.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/PlaceSearchForm/PlaceSearchForm.tsx
  src/components/MapgakcoMap/PlaceSearchForm/SearchResultList.tsx
  src/components/MapgakcoMap/SearchBar/SearchBar.tsx
  src/components/MapgakcoMap/SearchBar/styles.ts
  src/components/MapgakcoMap/styles.ts
  src/components/MapgakcoRegister/index.tsx
  src/constants/searchApi.ts
  src/types/place.ts
  src/utils/apis/search.ts
Labels: ♻️ refactor

#213 DVT-#207 대댓글 값 버그 수정
  src/components/UserDetail/Comment/index.tsx
Labels: fix

#217 DVT-#216 맵각코 지도 컴포넌트 검색 바 리팩터링
  src/components/Main/MapgakcoSummary/MapgakcoSummaryContainer.tsx
  src/components/MapgakcoMap/MapFloatControl/index.tsx
  src/components/MapgakcoMap/MapFloatControl/styles.ts
  src/components/MapgakcoMap/MapgakcoMap.tsx
  src/components/MapgakcoMap/styles.ts
  src/components/UsersMap/UsersMap.tsx
Labels: ♻️ refactor

#218 DVT-#212 탑바 유저 드랍다운 메뉴에 드랍다운 UI 추가
  src/components/UserImageAndDropdown/UserImageAndDropdown.tsx
  src/components/UserImageAndDropdown/styles.ts
Labels: feat

#222 DVT-#221 맵각코 지도 컨트롤 버튼 리팩토링
  src/components/MapgakcoMap/FilterButton.tsx
  src/components/MapgakcoMap/MapFloatControl/index.tsx
  src/components/MapgakcoMap/MapFloatControl/styles.ts
  src/components/MapgakcoMap/styles.ts
Labels: ♻️ refactor

#224 DVT-#223 공통 버튼 리팩토링
  src/components/CommentButton/CommentButton.tsx
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherDetail/styles.ts
  src/components/GatherMain/GatherMain.tsx
  src/components/GatherMain/styles.ts
  src/components/GatherRegisterForm/GatherRegisterForm.tsx
  src/components/GatherRegisterForm/styles.ts
  src/components/LikeButton/LikeButton.tsx
  src/components/Logo/Logo.tsx
  src/components/Main/Main.tsx
  src/components/Main/styles.ts
  src/components/MyGather/MyGather.tsx
  src/components/MyGather/styles.ts
  src/components/base/IconButton/index.ts
  src/components/base/Modal/index.tsx
  src/components/base/Modal/styles.ts
Labels: ♻️ refactor

#226 DVT-#225 맵각코 상세 페이지의 버튼 리팩터
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnEdit/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnEdit/styles.ts
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx
  src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/styles.ts
  src/components/base/OldButton/index.tsx
  src/components/base/OldButton/styles.ts
Labels: ♻️ refactor

#228 DVT-#227 Input 컴포넌트가 공통 컴포넌트 사용하도록 리팩터링
  src/assets/theme.ts
  src/components/GatherDetail/Comment/index.tsx
  src/components/GatherDetail/GatherDetail.tsx
  src/components/GatherRegisterForm/GatherRegisterForm.tsx
  src/components/Login/Login.tsx
  src/components/Login/styles.ts
  src/components/MapgakcoMap/PlaceSearchForm/PlaceSearchForm.tsx
  src/components/MapgakcoRegister/index.tsx
  src/components/MyProfile/MyProfile.tsx
  src/components/SearchForm/index.tsx
  src/components/SearchForm/styles.ts
  src/components/Signup/Signup.tsx
  src/components/Signup/styles.ts
  src/components/UserDetail/Comment/index.tsx
  src/components/UserDetail/UserDetail.tsx
  src/components/UserList/UserList.tsx
  src/components/base/Input/HiddenInput.ts
  src/components/base/Input/Input.tsx
  src/components/base/Input/index.ts
  src/components/base/Input/styles.ts
  src/components/base/Input/types.ts
Labels: ♻️ refactor
